---

# ####################################################################
#                             Prechecks
# ####################################################################

- name: Prechecks
  ansible.builtin.include_tasks: precheck.yml
  tags:
    - always

# ####################################################################
#                             Prerequisites
# ####################################################################

- name: Prerequisites
  ansible.builtin.include_tasks: prerequisites.yml

# ####################################################################
#                             Install k2d
# ####################################################################

- name: Install k2d
  ansible.builtin.include_tasks: install.yml
