---

- name: Add GPG apt keys
  ansible.builtin.apt_key:
    url: "{{ item }}"
    state: present
  become: true
  loop:
    - https://download.docker.com/linux/{{ ansible_distribution if not is_raspberry else 'raspbian' }}/gpg

- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
  become: true
  loop:
    - "deb https://download.docker.com/linux/{{ ansible_distribution if not is_raspberry else 'raspbian' }} {{ ansible_distribution_release }} stable"

- name: Install prerequisite Packages
  ansible.builtin.apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
  become: true

- name: Update apt and install docker-ce
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: true
  become: true

- name: Add docker group to user {{ ansible_user }}
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups: docker
  become: true
